### ISSUE TITLE
channels extraction

### ISSUE THREAD

**Issue by ansanto** [hcab14/signal-analysis#1]
since the tables for T207 14-bit format, I'd like to add the extraction of the two channels as following (after:   [m,i] = max(success);):
  
   fid2 =fopen ("ch_a.txt", "w"); 
   fid3 =fopen ("ch_b.txt", "w");   
  if (bd ==100)
    #extract channels a,b for 100Bd and CIS-14
    #1a 1b 2a 2b 3a 3b 4a 4b 5a 5b 6a 6b 
    fdisp (fid2, num2str(+frames{i} (:,1:2:11)));
    fdisp (fid3, num2str(+frames{i} (:,2:2:12)));
  else
    #extract channels a,b for 47.5, 50, 84.21, 94 Baud
    #1a 2a 3a 4a 5a 6a 1b 2b 3b 4b 5b 6b  
    fdisp (fid2, num2str(+frames{i} (:,1:6)));
    fdisp (fid3, num2str(+frames{i} (:,7:12)));   
  endif
  fclose(fid2);
  fclose(fid3);

Tested and working.

**Comment by hcab14** [comment]
What you need for this is the aligned matrix with frames.
Please have a look at the latest commit which returns it as 2nd return value.

Let me know if it works.

**Comment by ansanto** [comment]
hello Christoph

I do not see the two matrices, maybe they are displayed overlapped?
Anyway I need to save the two success matrices to disk for surther
elaborations such as decoding and so on. I'm also working on a fork of
T207_test.m adding the tests for the complete T-207 paradigm. I will be
more accurate soon, just the time to test the script :)

Ciao,
Antonio


2018-06-03 12:14 GMT+02:00 Christoph Mayer <notifications@github.com>:

**Comment by hcab14** [comment]
Hi Antonio,

the latest commit should have fixed this and it also includes a search for all 24 permutations of [0,1,2,3]. Let me know if there is something else to do.

Cheers
Christoph

**Comment by ansanto** [comment]
hi again Christoph

I spent last two days around TDoA  but I had time to run T207_detect.m and
it seems ok. I have still to write down a separate script to get output
from T207_detect, split the success matrix and then save the channels data
to disk (as you suggested in a previous email).

Ciao,
Antonio




2018-06-10 16:51 GMT+02:00 Christoph Mayer <notifications@github.com>:
